server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackUri: forward:/fallbackUserService
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - name: Path
          args:
            name: /departments/**
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackUri: forward:/fallbackDepartmentService


    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 4000