server:
  port: 9002
  
spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./appdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9192
    name: application.yaml
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true